import { LawFirm, Topic, LegalAreaId } from './types';

export const COUNTRIES = [
  "Argentina", "Brazil", "Canada", "Chile", "Colombia", "Mexico", "Peru", "United States",
  "Australia", "China", "India", "Japan", "Korea", "New Zealand", "Singapore", "Taiwan", "Thailand",
  "Austria", "Belgium", "Czech Republic", "Denmark", "Finland", "France", "Germany", "Greece",
  "Hungary", "Ireland", "Italy", "Luxembourg", "Netherlands", "Norway", "Poland", "Portugal",
  "Romania", "Spain", "Sweden", "Switzerland", "United Kingdom", "Israel", "Saudi Arabia",
  "Turkey", "United Arab Emirates"
];

export const PHARMA_AREAS = [
  "R&D / Discovery", "Clinical Development / Clinical Operations", "Pharmacovigilance / Drug Safety",
  "Medical Affairs", "Patient Support / Hubs / Copay / PAPs", "Commercial – Marketing and Omnichannel",
  "Commercial – Field Sales / Field Force", "Market Access / Pricing and Reimbursement",
  "HEOR / Real-World Evidence and Analytics", "Digital Health / Connected Solutions / Apps",
  "Manufacturing / Supply Chain / TechOps", "Quality Complaints / Product Quality",
  "IT Infrastructure / Cybersecurity / IAM", "Data Platforms / Analytics / Enterprise AI",
  "Human Resources / People and Culture", "Finance / Procurement / Vendor Management",
  "Legal / Privacy / Regulatory Intelligence", "Compliance and Ethics",
  "Corporate Communications / Public Affairs"
];

export const LEGAL_TOPICS: Topic[] = [
  { id: LegalAreaId.PRIVACY, label: "Privacy / Data Protection", icon: "Shield" },
  { id: LegalAreaId.AI, label: "AI / Automated Decision-Making", icon: "Bot" },
  { id: LegalAreaId.CYBERSECURITY, label: "Cybersecurity / Incident Reporting", icon: "Lock" },
  { id: LegalAreaId.HEALTH_INFO, label: "Health Information / HIPAA-type", icon: "HeartPulse" },
  { id: LegalAreaId.PATIENT_SUPPORT, label: "Patient Support Programs", icon: "Users" },
  { id: LegalAreaId.CONSENT_TRACKING, label: "Consent, Digital Tracking & Privacy Notices", icon: "Cookie" },
];

// Top 20 Largest Global Law Firms (by revenue/headcount from Am Law 100 & Global 200)
export const TOP_20_FIRMS: LawFirm[] = [
  { name: "Kirkland & Ellis", url: "https://www.kirkland.com/services/practices/intellectual-property/cybersecurity-data-privacy", category: "Top 20 Global Firms" },
  { name: "Latham & Watkins", url: "https://www.lw.com/en/practices/artificial-intelligence", category: "Top 20 Global Firms" },
  { name: "DLA Piper", url: "https://www.dlapiperdataprotection.com", category: "Top 20 Global Firms" },
  { name: "Baker McKenzie", url: "https://resourcehub.bakermckenzie.com/en/resources/global-data-and-cyber-handbook", category: "Top 20 Global Firms" },
  { name: "Skadden", url: "https://www.skadden.com/capabilities/practices/cybersecurity-and-data-privacy", category: "Top 20 Global Firms" },
  { name: "Sidley Austin", url: "https://datamatters.sidley.com", category: "Top 20 Global Firms" },
  { name: "Jones Day", url: "https://www.jonesday.com/en/practices/cybersecurity-privacy-and-data-protection", category: "Top 20 Global Firms" },
  { name: "Hogan Lovells", url: "https://www.hldataprotection.com", category: "Top 20 Global Firms" },
  { name: "White & Case", url: "https://www.whitecase.com/insight-our-thinking/ai-watch-global-regulatory-tracker-united-states", category: "Top 20 Global Firms" },
  { name: "Gibson Dunn", url: "https://www.gibsondunn.com/practice/privacy-cybersecurity-and-data-innovation/", category: "Top 20 Global Firms" },
  { name: "Ropes & Gray", url: "https://www.ropesdataphiles.com", category: "Top 20 Global Firms" },
  { name: "Freshfields Bruckhaus Deringer", url: "https://www.freshfields.com/en/capabilities/practices/data-privacy-and-tech-regulation", category: "Top 20 Global Firms" },
  { name: "Linklaters", url: "https://www.linklaters.com/en/insights", category: "Top 20 Global Firms" },
  { name: "Cleary Gottlieb", url: "https://www.clearycyberwatch.com", category: "Top 20 Global Firms" },
  { name: "Davis Polk", url: "https://www.davispolk.com/practices/litigation/cybersecurity", category: "Top 20 Global Firms" },
  { name: "Covington & Burling", url: "https://www.insideprivacy.com", category: "Top 20 Global Firms" },
  { name: "Norton Rose Fulbright", url: "https://www.dataprotectionreport.com", category: "Top 20 Global Firms" },
  { name: "Morrison Foerster", url: "https://www.mofo.com/gdpr-european-privacy/gdpr-european-privacy-client-alerts", category: "Top 20 Global Firms" },
  { name: "WilmerHale", url: "https://www.wilmerhale.com/en/solutions/cybersecurity-and-privacy", category: "Top 20 Global Firms" },
  { name: "Mayer Brown", url: "https://www.mayerbrown.com/en/insights/resource-centers/cybersecurity-and-data-privacy-resource-center", category: "Top 20 Global Firms" },
];

// Patient Support Program Specialist Firms
export const PATIENT_SUPPORT_FIRMS: LawFirm[] = [
  { name: "Goodwin Procter", url: "https://www.goodwinlaw.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "Bass, Berry & Sims", url: "https://www.bassberry.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "Holland & Knight", url: "https://www.hklaw.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "Sheppard Mullin", url: "https://www.sheppardmullin.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "Quarles & Brady", url: "https://www.quarles.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "Reed Smith", url: "https://www.reedsmith.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "King & Spalding", url: "https://www.kslaw.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "Covington & Burling", url: "https://www.cov.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "White & Case", url: "https://www.whitecase.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "Foley & Lardner", url: "https://www.foley.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "Epstein Becker Green", url: "https://www.ebglaw.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "McDermott Will & Emery", url: "https://www.mwe.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "Husch Blackwell", url: "https://www.huschblackwell.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "Mintz", url: "https://www.mintz.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "Ropes & Gray", url: "https://www.ropesgray.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "Hyman, Phelps & McNamara", url: "https://hpm.com", category: "Patient Support Programs", specialty: ["patient_support"] },
  { name: "Arnall Golden Gregory", url: "https://www.agg.com", category: "Patient Support Programs", specialty: ["patient_support"] },
];

// Extracted from PDF tables
export const LAW_FIRMS: LawFirm[] = [
  { name: "DLA Piper", url: "https://www.dlapiperdataprotection.com" },
  { name: "Baker McKenzie", url: "https://resourcehub.bakermckenzie.com/en/resources/global-data-and-cyber-handbook" },
  { name: "Hogan Lovells", url: "https://www.hldataprotection.com" },
  { name: "Morrison Foerster", url: "https://www.mofo.com/gdpr-european-privacy/gdpr-european-privacy-client-alerts" },
  { name: "Bird & Bird", url: "https://www.twobirds.com/en/capabilities/practices/privacy-and-data-protection" },
  { name: "Wilson Sonsini", url: "https://www.wsgr.com/en/services/practice-areas/regulatory/data-privacy-and-cybersecurity.html" },
  { name: "Proskauer", url: "https://privacylaw.proskauer.com" },
  { name: "Sidley Austin", url: "https://datamatters.sidley.com" },
  { name: "Hunton Andrews Kurth", url: "https://www.huntonprivacyblog.com" },
  { name: "Covington & Burling", url: "https://www.insideprivacy.com" },
  { name: "Perkins Coie", url: "https://perkinscoie.com/services/global-data-protection-laws" },
  { name: "Latham & Watkins", url: "https://www.lw.com/en/practices/artificial-intelligence" },
  { name: "Linklaters", url: "https://www.linklaters.com/en/insights" },
  { name: "Cooley", url: "https://www.cooley.com/services/practice/cyber-data-privacy/gdpr" },
  { name: "Debevoise & Plimpton", url: "https://www.debevoisedatablog.com" },
  { name: "Mayer Brown", url: "https://www.mayerbrown.com/en/insights/resource-centers/cybersecurity-and-data-privacy-resource-center" },
  { name: "Gibson Dunn", url: "https://www.gibsondunn.com/practice/privacy-cybersecurity-and-data-innovation/" },
  { name: "Ropes & Gray", url: "https://www.ropesdataphiles.com" },
  { name: "Goodwin Procter", url: "https://www.goodwinprivacyblog.com" },
  { name: "Norton Rose Fulbright", url: "https://www.dataprotectionreport.com" },
  { name: "Freshfields Bruckhaus Deringer", url: "https://www.freshfields.com/en/capabilities/practices/data-privacy-and-tech-regulation" },
  { name: "Alston & Bird", url: "https://www.alston.com" },
  { name: "Greenberg Traurig", url: "https://www.gtlaw-dataprivacydish.com" },
  { name: "Paul Hastings", url: "https://www.paulhastings.com/insights/ph-privacy" },
  { name: "Troutman Pepper", url: "https://www.troutman.com/insights/more-privacy-please.html" },
  { name: "Orrick", url: "https://www.orrick.com/en/Practices/Cyber-Privacy-Data-Innovation" },
  { name: "BakerHostetler", url: "https://www.dataprivacymonitor.com" },
  { name: "Dechert", url: "https://www.dechert.com/knowledge/hot-topic/privacy---cybersecurity.html" },
  { name: "WilmerHale", url: "https://www.wilmerhale.com/en/solutions/cybersecurity-and-privacy" },
  { name: "Jones Day", url: "https://www.jonesday.com/en/practices/cybersecurity-privacy-and-data-protection" },
  { name: "Venable", url: "https://www.venable.com/services/practices/advertising-and-marketing/privacy-and-data-security" },
  { name: "Fox Rothschild", url: "https://dataprivacy.foxrothschild.com" },
  { name: "Mintz", url: "https://www.mintz.com/insights-center/topics/privacy-cybersecurity" },
  { name: "Polsinelli", url: "https://www.polsinelli.com/hipaa-health-information-privacy-security" },
  { name: "Eversheds Sutherland", url: "https://www.eversheds-sutherland.com/global/en/what/practices/data-privacy-cybersecurity/index.page" },
  { name: "Fenwick & West", url: "https://www.fenwick.com/services/practices/privacy-cybersecurity" },
  { name: "Sheppard Mullin", url: "https://www.datasecuritylawblog.com" },
  { name: "Skadden", url: "https://www.skadden.com/capabilities/practices/cybersecurity-and-data-privacy" },
  { name: "McDermott Will & Emery", url: "https://www.mwe.com/services/privacy-cybersecurity/" },
  { name: "Arnold & Porter", url: "https://www.arnoldporter.com/en/services/practices/advisory/privacy-and-data-security" },
  { name: "White & Case", url: "https://www.whitecase.com/insight-our-thinking/ai-watch-global-regulatory-tracker-united-states" },
  { name: "Cleary Gottlieb", url: "https://www.clearycyberwatch.com" },
  { name: "Kirkland & Ellis", url: "https://www.kirkland.com/services/practices/intellectual-property/cybersecurity-data-privacy" },
  { name: "Holland & Knight", url: "https://www.hklaw.com/en/services/practices/healthcare/hipaa-and-healthcare-privacy" },
  { name: "Crowell & Moring", url: "https://www.crowelldatalaw.com" },
  { name: "King & Spalding", url: "https://www.kslaw.com/capabilities/data-privacy-and-cybersecurity" },
  { name: "Reed Smith", url: "https://www.reedsmith.com/en/capabilities/services/data-privacy-security-and-management" },
  { name: "Davis Wright Tremaine", url: "https://www.dwt.com/blogs/privacy--security-law-blog" },
  { name: "Davis Polk", url: "https://www.davispolk.com/practices/litigation/cybersecurity" },
  { name: "Hintze Law", url: "https://hintzelaw.com/blog" },
  { name: "Clyde & Co", url: "https://www.clydeco.com/en/insights" },
  
  // Asia Pacific & Others (Flattening the list for the dropdown)
  { name: "Mori Hamada & Matsumoto (Japan)", url: "https://mhmjapan.com/publications", region: "Japan" },
  { name: "Nagashima Ohno & Tsunematsu (Japan)", url: "https://noandt.com/publications", region: "Japan" },
  { name: "Anderson Mori & Tomotsune (Japan)", url: "https://amt-law.com/publications", region: "Japan" },
  { name: "Atsumi & Sakai (Japan)", url: "https://aplawjapan.com/publications", region: "Japan" },
  { name: "Oh-Ebashi LPC & Partners (Japan)", url: "https://ohebashi.com/news", region: "Japan" },
  { name: "Zhong Lun Law Firm (China)", url: "https://en.zhonglun.com", region: "China" },
  { name: "JunHe LLP (China)", url: "https://junhe.com", region: "China" },
  { name: "Fangda Partners (China)", url: "https://fangdalaw.com", region: "China" },
  { name: "Global Law Office (China)", url: "https://glo.com.cn", region: "China" },
  { name: "DaHui Lawyers (China)", url: "https://dahuilawyers.com", region: "China" },
  { name: "Kim & Chang (Korea)", url: "https://kimchang.com/insights", region: "South Korea" },
  { name: "Yulchon LLC (Korea)", url: "https://yulchon.com", region: "South Korea" },
  { name: "Lee & Ko (Korea)", url: "https://leeko.com", region: "South Korea" },
  { name: "Drew & Napier LLC (Singapore)", url: "https://drewnapier.com/insights", region: "Singapore" },
  { name: "Rajah & Tann Singapore", url: "https://rajahtannasia.com/publications", region: "Singapore" },
  { name: "WongPartnership (Singapore)", url: "https://wongpartnership.com/knowledge", region: "Singapore" },
  { name: "Cyril Amarchand Mangaldas (India)", url: "https://cyrilamarchandblogs.com", region: "India" },
  { name: "Nishith Desai Associates (India)", url: "https://nishithdesai.com/research", region: "India" },
  { name: "AZB & Partners (India)", url: "https://azbpartners.com/bank", region: "India" },
  { name: "Trilegal (India)", url: "https://trilegal.com/knowledge", region: "India" },
  { name: "Gilbert + Tobin (Australia)", url: "https://www.gtlaw.com.au", region: "Australia" },
  { name: "Clayton Utz (Australia)", url: "https://claytonutz.com/insights", region: "Australia" },
  { name: "Corrs Chambers Westgarth (Australia)", url: "https://corrs.com.au/insights", region: "Australia" },
  { name: "Hall & Wilcox (Australia)", url: "https://hallandwilcox.com.au/thinking", region: "Australia" },
  { name: "Noerr (Germany)", url: "https://noerr.com/insights", region: "Germany" },
  { name: "Gleiss Lutz (Germany)", url: "https://gleisslutz.com/news", region: "Germany" },
  { name: "Hengeler Mueller (Germany)", url: "https://hengeler.com/news", region: "Germany" },
  { name: "Taylor Wessing (Germany)", url: "https://taylorwessing.com/insights", region: "Germany" },
  { name: "Heuking (Germany)", url: "https://www.heuking.de", region: "Germany" },
  { name: "PANETTA Studio Legale (Italy)", url: "https://intlipapers.com", region: "Italy" },
  { name: "Portolano Cavallo (Italy)", url: "https://www.portolano.it", region: "Italy" },
  { name: "ICTLC - ICT Legal Consulting (Italy)", url: "https://ictlc.com/news", region: "Italy" },
  { name: "Orsingher Ortu (Italy)", url: "https://orsingherortu.com/news", region: "Italy" },
  { name: "Mattos Filho (Brazil)", url: "https://www.mattosfilho.com.br", region: "Brazil" },
  { name: "Pinheiro Neto Advogados (Brazil)", url: "https://pinheironeto.com.br/knowledge", region: "Brazil" },
  { name: "TozziniFreire Advogados (Brazil)", url: "https://tozzinifreire.com.br/publications", region: "Brazil" },
  { name: "Trench Rossi Watanabe (Brazil)", url: "https://trenchrossi.com/insights", region: "Brazil" },
  { name: "Davara Abogados (Mexico)", url: "https://davara.com.mx", region: "Mexico" },
  { name: "PAG Law (Mexico)", url: "https://pag.law/publications", region: "Mexico" },
  { name: "Sánchez Devanny (Mexico)", url: "https://sanchezdevanny.com/insights", region: "Mexico" },
  { name: "Al Tamimi & Company (UAE)", url: "https://www.tamimi.com", region: "UAE" },
  { name: "GLA & Company (UAE)", url: "https://glaco.com", region: "UAE" },
  { name: "BSA Ahmad Bin Hezeem (UAE)", url: "https://bsabh.com/insights", region: "UAE" }
];